name: cd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make application-prod.yml
        run: |
          cd ./src/main/resources
          touch ./application-prod.yml
          echo "${{ secrets.APPLICATION_PROD }}" > ./application-prod.yml
        shell: bash

      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew
        
      - name: Build With Gradle
        run: ./gradlew build

      - name: Docker build & push to docker repo
        env:
          DOCKER_PATH : .deploy/Dockerfile
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f $DOCKER_PATH -t ${{ secrets.DOCKER_REPO }}/mookive .
          docker push ${{ secrets.DOCKER_REPO }}/mookive


      - name: Deploy to server
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          envs: GITHUB_SHA
          script: |
             docker stop mookive
             docker rm mookive
             sudo docker pull ${{ secrets.DOCKER_REPO }}/mookive
             docker run -d --name goorm -p 8080:8080 ${{ secrets.DOCKER_REPO }}/mookive
             docker rmi -f $(docker images -f "dangling=true" -q)
